blogicum/blog/urls.py
from django.urls import include, path

from blog import views

app_name = 'blog'

posts_urls = [
    path(
        '<int:post_id>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'create/',
        views.PostCreateView.as_view(),
        name='create_post'
    ),
    path(
        '<int:post_id>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'
    ),
    path(
        '<int:post_id>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'
    ),


    path('<int:post_id>/comment/',
         views.CommentCreateView.as_view(),
         name='add_comment'),
    path(
        '<int:post_id>/edit_comment/<int:comment_id>/',
        views.CommentUpdateView.as_view(),
        name='edit_comment'
    ),
    path(
        '<int:post_id>/delete_comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(),
        name='delete_comment'
    ),
]


urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path(
        'category/<slug:post_category>/',
        views.CategoryListView.as_view(),
        name='category_posts'
    ),

    path(
        'profile/<slug:username>/',
        views.ProfileDetailView.as_view(),
        name='profile'
    ),
    path(
        'edit_profile/',
        views.UserUpdateView.as_view(),
        name='edit_profile'
    ),
    path('posts/', include(posts_urls)),
]

blogicum/blogicum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from blog.views import UserCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls', namespace='pages')),
    path('auth/registration/', UserCreateView.as_view(), name='registration'),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('blog.urls', namespace='blog')),
]

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

if settings.DEBUG:
    """Если проект запущен в режиме разработки,
    dобавить к списку urlpatterns список адресов из приложения debug_toolbar.
    """

    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

blogicum/pages/urls.py
from django.urls import path

from pages import views

app_name = 'pages'

urlpatterns = [
    path(
        'about/',
        views.AboutTemplateView.as_view(),
        name='about'
    ),
    path(
        'rules/',
        views.RulesTemplateView.as_view(),
        name='rules'
    )
]

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    slug = models.SlugField(unique=True)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Location(models.Model):
    name = models.CharField(max_length=256)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blogicum/core/models.py
from django.db import models


class PublishedModel(models.Model):
    """Абстрактная модель. Добвляет флаг опубликовано и дату добавления."""

    is_published = models.BooleanField(
        'Опубликовано',
        default=True,
        help_text='Снимите галочку, чтобы скрыть публикацию.'
    )
    created_at = models.DateTimeField(
        'Добавлено',
        auto_now_add=True
    )

    class Meta:
        abstract = True

blogicum/blog/forms.py
from django import forms

from blog.models import Comment, Post, User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        exclude = ('author',)
        widgets = {
            'pub_date': forms.DateTimeInput(
                format='%Y-%m-%d %H:%M', attrs={'type': 'datetime-local'}
            ),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(
                attrs={'cols': 10, 'rows': 4})
        }

blogicum/blog/views.py
from django.shortcuts import render
from .models import Post

def index(request):
    posts = Post.objects.filter(
        pub_date__lte=timezone.now(),
        is_published=True,
        category__is_published=True
    ).order_by('-pub_date')[:5]
    return render(request, 'index.html', {'page_obj': posts})

blogicum/pages/views.py
# pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class AboutTemplateView(TemplateView):
    template_name = 'pages/about.html'

class RulesTemplateView(TemplateView):
    template_name = 'pages/rules.html'

def csrf_failure(request, reason=''):
    return render(request, 'pages/403csrf.html', status=403)

def page_not_found(request, exception):
    return render(request, 'pages/404.html', status=404)

def server_error(request):
    return render(request, 'pages/500.html', status=500)

blogicum/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Публикации в категории - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Редактирование комментария
  {% else %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Редактирование комментария
          {% else %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

blogicum/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
{% if '/edit/' in request.path %}
Редактирование публикации
{% elif "/delete/" in request.path %}
Удаление публикации
{% else %}
Добавление публикации
{% endif %}
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header">
      {% if '/edit/' in request.path %}
      Редактирование публикации
      {% elif '/delete/' in request.path %}
      Удаление публикации
      {% else %}
      Добавление публикации
      {% endif %}
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if not '/delete/' in request.path %}
        {% bootstrap_form form %}
        {% else %}
        <article>
          {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ post.image.url }}">
          </a>
          {% endif %}
          <p>{{ post.pub_date|date:"d E Y" }} |
            {% if post.location and post.location.is_published%}{{ post.location.name }}
            {% else %}Планета Земля{% endif %}<br>
          <h3>{{ post.title }}</h3>
          <p>{{ post.text|linebreaksbr }}</p>
        </article>
        {% endif %}
        {% bootstrap_button button_type="submit" content="Отправить" %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %} |
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
            От автора <a class="text-muted" href="{% url 'blog:profile' post.author %}">@{{ post.author.username }}</a> в
            категории {% if post.category %}{% include "includes/category_link.html" %}{% else %}Не задано.{% endif %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        {% if user == post.author %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'blog:edit_post' post.id %}" role="button">
              Отредактировать публикацию
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'blog:delete_post' post.id %}" role="button">
              Удалить публикацию
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
Страница пользователя {{ profile }}
{% endblock %}
{% block content %}
<h1 class="mb-5 text-center ">Страница пользователя {{ profile }}</h1>
<small>
  <ul class="list-group list-group-horizontal justify-content-center mb-3">
    <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}
      {% else %}не указано{% endif %}</li>
    <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
    <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
  </ul>
  <ul class="list-group list-group-horizontal justify-content-center">
    {% if user.is_authenticated and request.user == profile %}
    <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' %}">Редактировать профиль</a>
    <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
    {% endif %}
  </ul>
</small>
<br>
<h3 class="mb-5 text-center">Публикации пользователя</h3>
{% for post in page_obj %}
<article class="mb-5">
  {% include "includes/post_card.html" %}
</article>
{% endfor %}
{% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  {{ post.category.title }}
</a>

blogicum/templates/includes/comments.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <h5 class="mb-4">Оставить комментарий</h5>
  <form method="post" action="{% url 'blog:add_comment' post.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Отправить" %}
  </form>
{% endif %}
<br>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'blog:profile' comment.author.username %}" name="comment_{{ comment.id }}">
          @{{ comment.author.username }}
        </a>
      </h5>
      <small class="text-muted">{{ comment.created_at }}</small>
      <br>
      {{ comment.text|linebreaksbr }}
    </div>
    {% if user == comment.author %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_comment' post.id comment.id %}" role="button">
        Отредактировать комментарий
      </a>
      <a class="btn btn-sm text-muted" href="{% url 'blog:delete_comment' post.id comment.id %}" role="button">
        Удалить комментарий
      </a>
    {% endif %}
  </div>
{% endfor %}

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav  nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
            О проекте
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:rules' %} text-white {% endif %}" href="{% url 'pages:rules' %}">
            Правила
          </a>
        </li>
        {% if user.is_authenticated %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'blog:create_post' %}">Написать пост</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'logout' %}">Выйти</a></button>
        </div>
        {% else %}
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'login' %}">Войти</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'registration' %}">Регистрация</a></button>
        </div>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>
</header>

blogicum/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

blogicum/templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% elif post.category %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
            От автора <a class="text-muted" href="{% url 'blog:profile' post.author %}">@{{ post.author.username }}</a> в
            категории {% include "includes/category_link.html" %}
          {% else %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
            От автора <a class="text-muted" href="{% url 'blog:profile' post.author %}">@{{ post.author.username }}</a>
          {% endif %}
        </small>
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link text-muted">Комментарии ({{ post.num_comments }})</a>
    </div>
  </div>
</div>

blogicum/templates/pages/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'blog:index' %}">Вернуться на главную</a>
{% endblock %}

blogicum/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        О проекте
      </div>
      <div class="card-body">
        <p>
          Блогикум — это дом для творческих людей. Это — сообщество людей, для которых
          нет грани между ведением блога и дружбой в социальных сетях.
        </p>
        <p>
          Дружба и рассказы о новых, неизведанных впечатлениях — вот
          что вы найдете на нашем ресурсе. Миллионы блогов по различным темам.
          Путешествия, политика, развлечения, мода, литература, дизайн и все
          другие сферы человеческой деятельности.
        </p>
        <p>
          Творчество, разнообразие и свобода взглядов и самовыражения —
          основные черты наших пользователей.
        </p>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Правила сайта
      </div>
      <div class="card-body">
        <p>
          <b>Cамовыражение.</b> У наших пользователей должна
          быть возможность создать что-то своё, выразить себя,
          свои мысли и чувства.
        </p>
        <p>
          <b>Многообразие.</b> Мы уважаем и приветствуем разные
          мнения и культуры. Блогикум — это место, объединяющее
          самых разных людей. Поделитесь своим уникальным взглядом на мир.
        </p>
        <p>
          <b>Творчество.</b> Не важно, в какой области вы творите,
          это может быть литература, дизайн, программирование.
          Наши инструменты помогут вам раскрыть талант максимально
          просто и комфортно.
        </p>
        <p>
          <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
          Делитесь своей информацией только с теми, кого выбрали.
          Как и насколько засекречивать вашу личную информацию —
          определяете вы и только вы.
        </p>
      </div>
    </div>
  </div>
{% endblock %}